[package]
name = "resurs"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "storage"
harness = false

[dependencies]
