[package]
name = "ramneryd"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.15.0"
specs-hierarchy = "0.5.1"
specs-derive = "0.4.0"

# Rendering/Graphics
vulkano = { git = "https://github.com/NiklasJonsson/vulkano" }
winit = "0.19"
vulkano-win = { git = "https://github.com/NiklasJonsson/vulkano" }
vulkano-shaders = { git = "https://github.com/NiklasJonsson/vulkano" }
vk-sys = { git = "https://github.com/NiklasJonsson/vulkano" }

# Math/Physics
nalgebra-glm = "0.4.0"
num-derive = "0.2.5"
num-traits = "0.2.8"

# Resources/Assets
image = "0.22.1"
tobj = "0.1.10"
gltf = "0.13.0"

# Util
log = "0.4.8"
env_logger = "0.6.2"
