[package]
name = "vulkan-experiments"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "*"
winit = "*"
vulkano-win = "*"
vulkano-shaders = "*"
nalgebra-glm = "*"
image = "*"
num-derive = "*"
num-traits = "*"
tobj = "*"
