[package]
name = "ramneryd"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
specs-hierarchy = "0.6.0"
specs = { version = "0.16.1", features = ["specs-derive"] }

# Rendering/Graphics
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
winit = "0.19"
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano" }
vk-sys = { git = "https://github.com/vulkano-rs/vulkano" }

# Math/Physics
nalgebra-glm = "0.4.0"
num-derive = "0.2.5"
num-traits = "0.2.8"

# Resources/Assets
image = "0.22.1"
tobj = "0.1.10"
gltf = "0.14.0"

# Util
log = "0.4.8"
env_logger = "0.6.2"
clap = "2.33.0"
