[package]
name = "ramneryd"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
specs = "*"
specs-derive = "*"

# Rendering/Graphics
vulkano = { git = "https://github.com/NiklasJonsson/vulkano" }
winit = "0.19"
vulkano-win = { git = "https://github.com/NiklasJonsson/vulkano" }
vulkano-shaders = { git = "https://github.com/NiklasJonsson/vulkano" }
vk-sys = { git = "https://github.com/NiklasJonsson/vulkano" }

# Math/Physics
nalgebra-glm = "*"
num-derive = "*"
num-traits = "*"

# Resources/Assets
image = "*"
tobj = "*"
gltf = "*"

# Util
log = "*"
env_logger = "*"
