[package]
name = "ramneryd"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
specs = "*"
specs-derive = "*"

# Rendering/Graphics
vulkano = "*"
winit = "*"
vulkano-win = "*"
vulkano-shaders = "*"
vk-sys = "*"

# Math/Physics
nalgebra-glm = "*"
num-derive = "*"
num-traits = "*"

# Resources/Assets
image = "*"
tobj = "*"
gltf = "*"

# Util
log = "*"
env_logger = "*"
