[package]
name = "gltf-viewer"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2018"

[dependencies]
ramneryd = {path = "../ramneryd" }
structopt = "*"

[features]
profile = ["ramneryd/profile-with-tracy"]
