[package]
name = "editor"
version = "0.1.0"
authors = ["Niklas Jonsson <niklasandersjonsson@gmail.com>"]
edition = "2021"

[dependencies]
ramneryd = { path = "../ramneryd", features = ["validation-layers"] }
structopt = "*"

[features]
profile = ["ramneryd/profile-with-tracy"]
